import QuestionSidebar from "@/components/sidebar/QuestionSidebar";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <QuestionSidebar /> */}
        {children}
      </body>
    </html>
  );
}
