import QuestionSidebar from "@/components/sidebar/QuestionSidebar";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <QuestionSidebar /> */}
        <SidebarProvider defaultOpen={false}>{children}</SidebarProvider>
      </body>
    </html>
  );
}
